#!/bin/sh
# See https://www.debian.org/doc/debian-policy/
#

set -e

case "$1" in
    configure)
        if [ $(command -v systemctl) > /dev/null ]; then
            cp -fp /opt/ljdelight/rawdisk/ljdelight-rawdisk.service /etc/systemd/system/
            systemctl --quiet enable ljdelight-rawdisk.service > /dev/null
            systemctl --quiet start ljdelight-rawdisk.service > /dev/null
        elif [ $(command -v update-rc.d) > /dev/null ]; then
            ln -s /opt/ljdelight/rawdisk/ljdelight-rawdisk.init /etc/init.d/ljdelight-rawdisk
            update-rc.d ljdelight-rawdisk defaults > /dev/null
            service ljdelight-rawdisk start > /dev/null
        else
            echo "postinst could not register ljdelight-rawdisk: no systemctl nor update-rc.d" >&2
            exit 1
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
