#!/bin/sh
# See https://www.debian.org/doc/debian-policy/

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        if [ $(command -v systemctl) > /dev/null ]; then
            systemctl --quiet stop  ljdelight-rawdisk.service > /dev/null
            systemctl --quiet disable ljdelight-rawdisk.service > /dev/null
            rm -f /etc/systemd/system/ljdelight-rawdisk.service
            systemctl daemon-reload
        elif [ $(command -v update-rc.d) > /dev/null ]; then
            service ljdelight-rawdisk stop > /dev/null
            update-rc.d ljdelight-rawdisk remove > /dev/null
            rm -f /etc/init.d/ljdelight-rawdisk
        else
            echo "postrm could not determine systemctl or update-rc.d" >&2
            exit 1
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
